Pie chart 2way sync
opensearch-project/observability pull request #1029
Opened 2022-09-16 05:37 UTC by ramneet-persistent

### Description
- Pie chart two way sycn as per #987 
- mode bug resolution
- UI Issues fixes

### Issues Resolved
[mode bug](https://github.com/opensearch-project/observability/issues/965)
[two way communication](https://github.com/opensearch-project/observability/issues/1010)

2022-09-16 12:34 UTC, spattnaik requested changes

2022-09-16 12:34 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/utils/utils.tsx
> +  } else if (tooltipText === undefined) {
There is no requirement of `else`. You can write `if` directly.

2022-09-16 23:28 UTC, mengweieric approved these changes

2022-09-19 11:08 UTC, abasatwar approved these changes

2022-09-20 06:16 UTC, ramneet-persistent commented on dashboards-observability/common/constants/explorer.ts
> +export const numericalTypes = [
will update all comments in separate PR

2022-09-23 20:43 UTC, sejli approved these changes

2022-09-23 20:46 UTC, mengweieric approved these changes

2022-09-23 20:46 UTC, merged