Adhereing to tenancy access roles in observability CRUD operations
opensearch-project/observability pull request #1049
Opened 2022-09-28 17:10 UTC by vamsi-amazon

Signed-off-by: vamsi-amazon <reddyvam@amazon.com>

### Description
Adhering to tenancy access roles in Observability CRUD operations.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-05 18:27 UTC, derek-ho commented on opensearch-observability/src/main/kotlin/org/opensearch/observability/security/UserAccessManager.kt
> +    private fun getUserTenantAccess(user: User?): String {
user should not be nullable at this point?

2022-10-05 18:33 UTC, derek-ho commented on opensearch-observability/src/main/kotlin/org/opensearch/observability/action/ObservabilityActions.kt
> +                "Permission denied for ObservabilityObject creation",
I noticed in the exceptions below you are leaving it really generic i.e. "Permission denied for ObservailibtyObject ${id}", should this be the same?

2023-02-08 01:41 UTC, YANG-DB commented on opensearch-observability/src/main/kotlin/org/opensearch/observability/security/UserAccessManager.kt
> +    private const val WRITE_ACCESS = "WRITE"
should this also be an enum ?

2023-02-08 01:43 UTC, YANG-DB requested changes

2023-02-08 01:43 UTC, YANG-DB commented on opensearch-observability/src/main/kotlin/org/opensearch/observability/security/UserAccessManager.kt
> +        if (user == null) { // Security is disabled
isnt this a security risk ?

2023-02-08 17:15 UTC, vamsi-amazon commented
Closing this PR. will raise once we decided to go ahead with release.

2023-02-08 17:15 UTC, closed without merging