remove front end workflow and code
opensearch-project/observability pull request #1362
Opened 2023-01-03 19:26 UTC by derek-ho

Signed-off-by: Derek Ho <dxho@amazon.com>

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-03 19:41 UTC, derek-ho commented
@gaiksaya @zelinh I will wait for your go ahead before merging in this PR to get rid of front end code

2023-01-05 17:39 UTC, YANG-DB requested changes
@derek-ho I think  you should be promoting the [opensearch-observability] folder content to be in the root level

2023-01-05 18:00 UTC, derek-ho commented
> @derek-ho I think you should be promoting the [opensearch-observability] folder content to be in the root level

Done, thanks for catching it!

2023-01-06 21:55 UTC, YANG-DB approved these changes

2023-01-06 22:01 UTC, rupal-bq approved these changes

2023-01-06 22:28 UTC, merged