Baseline repo permissions code-owners and maintainers
opensearch-project/observability pull request #1439
Opened 2023-02-28 15:49 UTC by derek-ho

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-07 22:07 UTC, YANG-DB requested changes

2023-03-07 22:07 UTC, YANG-DB commented on CODEOWNERS
> +*   @pjfitzgibbons @anirudha @nknize @ps48 @kavithacm @derek-ho @joshuali925 @zhongnansu @dai-chen @sejli @YANG-DB @davidcui1225 @rupal-bq @CEHENKLE @mengweieric @eugenesk24 @vamsi-amazon @kavck
missing [Swiddis](https://github.com/Swiddis)

2023-03-07 22:07 UTC, YANG-DB commented on MAINTAINERS.md
>  | Eric Wei          | [mengweieric](https://github.com/mengweieric)     | Amazon      |
missing [Swiddis](https://github.com/Swiddis)

2023-03-15 17:19 UTC, YANG-DB requested changes

2023-03-31 16:19 UTC, ps48 submitted a review, later dismissed

2023-03-31 16:30 UTC, rupal-bq submitted a review, later dismissed

2023-04-25 19:16 UTC, anirudha approved these changes

2023-04-25 19:43 UTC, YANG-DB approved these changes

2023-04-25 21:44 UTC, bbarani commented
Ready to merge. Maintainers have been added. This CODEOWNERS file is valid.

2023-04-25 22:59 UTC, mengweieric approved these changes

2023-04-26 13:49 UTC, merged