Rename all SSO references to SS4O
opensearch-project/observability pull request #1470
Opened 2023-03-15 17:43 UTC by Swiddis

### Description

PR does what it says on the tin, per #1448 

The main substitution (minus one file rename) was done with the following shell command, it may be better to review this for bugs than the individual diffs:

```sh
grep -rli "[^a-z]sso[^a-z]" . --exclude-dir=.git | xargs sed -i -r 's/([^a-z]ss)(o[^a-z])/\14\2/i'
```

### Issues Resolved

Resolves #1448 

### Check List

- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-17 00:47 UTC, YANG-DB requested changes

2023-03-17 00:47 UTC, YANG-DB commented on integrations/nginx/assets/display/ss4o-logs-dashboard-new.ndjson
why this file was effected ? it doesn’t contain sso ...

2023-03-17 16:38 UTC, Swiddis commented on integrations/nginx/assets/display/ss4o-logs-dashboard-new.ndjson
It's in the `title`, column `8949`. `"title":"sso_logs-*-*"`

2023-03-17 16:52 UTC, Swiddis commented on integrations/nginx/info/nginx.png
Yep, that happens if you accidentally do a find-replace for a bytestring in a png.

For any future readers, you can use the `-I` flag in grep to tell it to skip binary files.

2023-03-20 15:05 UTC, derek-ho commented on docs/Integration-API.md
> +   - "index_patterns":` ["ss4o_logs-*-*"]` -> `["sso_logs-*-*", "myLogs-*"]`
miss one here?

2023-03-20 15:07 UTC, derek-ho commented on integrations/nginx/info/fluent-bit/fluentbit.png
why do these files need to be re-named? Am I missing something

2023-03-20 21:26 UTC, Swiddis commented on integrations/nginx/info/fluent-bit/fluentbit.png
Just correcting a misspelled directory name, technically not in the scope of the PR but seems harmless enough to just add it in. I can make it a separate PR if you prefer?

2023-03-20 21:40 UTC, Swiddis commented on src/main/kotlin/org/opensearch/observability/index/ObservabilityTracesIndex.kt
> +    private const val TRACES_MAPPING_TEMPLATE_NAME = "ss4o_trace_template"
I think one option is just add a deprecation warning. When integration plugin starts up, check for sso indices, and if present log a warning like `Detected indices with 'sso_*' pattern, which is deprecated. The new 'ss4o_*' pattern will be created and used by default`.

Even better would be making it configurable, which could be implemented at import-time. The import method could involve a step for checking for a configured index name, and if one is found, replace the integration's index patterns in-place.

2023-03-20 21:56 UTC, YANG-DB commented on src/main/kotlin/org/opensearch/observability/index/ObservabilityTracesIndex.kt
> +    private const val TRACES_MAPPING_TEMPLATE_NAME = "ss4o_trace_template"
agree

2023-03-20 21:59 UTC, YANG-DB submitted a review, later dismissed

2023-03-23 18:09 UTC, derek-ho approved these changes

2023-03-29 21:50 UTC, merged