api changes for UI
opensearch-project/observability pull request #1479
Opened 2023-03-23 17:58 UTC by derek-ho

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-23 18:09 UTC, YANG-DB requested changes

2023-03-23 18:09 UTC, YANG-DB commented on schema/system/integration-put.schema
why do we need an integration-put ? can't we just use the integration-instance for put operation as-well ?

2023-03-23 18:09 UTC, YANG-DB commented on docs/API/swagger.yaml
> +              $ref: '../../schema/system/integration-put.schema'
why do we need a dedicated resource for the put operation ? it is not a conventional  REST operation

2023-03-30 16:51 UTC, YANG-DB requested changes

2023-03-30 16:51 UTC, YANG-DB commented on schema/system/integration-put.schema
please remove this type - it is identical to the integration instance

2023-05-11 20:18 UTC, derek-ho commented on docs/API/swagger.yaml
> +              examples:
here

2023-05-22 18:43 UTC, Swiddis commented
@derek-ho what steps do we need to do in order to get this revised and merged? We really should be freezing our data interfaces soon.

2023-07-11 13:42 UTC, derek-ho commented
Closing, as we went forward with frontend plugin design

2023-07-11 13:42 UTC, closed without merging