[BUG] : Dimensions getting removed when no timeseries field is present
opensearch-project/observability pull request #944
Opened 2022-08-17 13:21 UTC by ruchika-narang

### Description
1. Resolved dimension issue for Time Series
2. Resolved issue of data configuration reset after change of PPL query.

### Issues Resolved
#942 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-17 13:47 UTC, abasatwar requested changes

2022-08-17 13:47 UTC, abasatwar commented on dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts
> +const getUserConfigs = (userSelectedConfigs: any, vizFields: IField[], visName: string) => {
avoid any

2022-08-17 13:47 UTC, abasatwar commented on dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts
> +              dimensions: [{ bucketSize: '', bucketOffset: '' }],
adding empty values will load chart?

2022-08-17 13:55 UTC, shankha-das commented on dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts
> +              dimensions: [{ bucketSize: '', bucketOffset: '' }],
Yes, it will load the chart.

2022-08-17 14:59 UTC, abasatwar approved these changes

2022-08-22 21:21 UTC, mengweieric approved these changes

2022-08-22 21:32 UTC, joshuali925 approved these changes

2022-08-22 21:36 UTC, merged